[project]
name = "time-series-library"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["torch>=2.11.0"]


[tool.setuptools.packages.find]
where = ["."]


[tool.pyright]

# override in parent class issue
reportIncompatibleMethodOverride = false


# Suppress the "__getitem__" not defined error specifically
reportIndexIssue = "none"
